### PR TITLE
JSON encode support for struct objects

### PR DESCRIPTION
**Pull request by sradinger**
Add StructJsonSerializeTrait to struct objects, to be able to json_encode objects

### CODE REVIEW

**Comment by usox** [comment]
First of all: Thanks for the PR! It needs to be discussed, though.

Json-Encoding the complete struct will expose all private properties (and will use them as object keys in the resulting json) - we won't be able to change them any longer. Second, every addition in the struct will be present in the resulting json, causing changed datasets on client side every time we add/change the internals.
@WorksDev Didn't we talk about adding multiple output formats in the soap connector?

**Comment by WorksDev** [comment]
Hi,

thanks also from my side for the contribution. 

@usox I mean yes, in future development stages - as long as there is a valid scenario for it. 

From my point of view, this is currently not the case for the reasons mentioned above.

@sradinger what are you trying to achieve with it?

**Comment by sradinger** [comment]
Thank you for your answers.
I understand your doubts.

I need the response for logging purposes as JSON.
For the further processing of the data I would like to use the created response object.

If the adjustments are not ok for you, you can ignore them and I will program an alternative without adjustments to this component.

**Comment by usox** [comment]
> I need the response for logging purposes as JSON.

Well, I guess we could consider adding a Logger to the connector to simply log all outgoing/incoming data. From my pov, it shouldn't be that hard.

> For the further processing of the data I would like to use the created response object.

I can image lots of use cases for structured json data and I think, it's a valid request. Imo the best way would be a mapping of the internal keys to external ones. This has to be done for every single method, though.

I.e. for the AccountingItem-Struct:
```
public function jsonSerialize(): array {
  return [
    'externalKeyForDescription' => $this->description,
    'externalKeyForMandatorId' => $this->mandatorId,
    'externalKeyForAccountingDate' => $this->accountingDate,
    'externalKeyForChargeCount' => $this->chargeCount,
  ];
}
```

**Comment by WorksDev** [comment]
@usox yes it's a valid request, that's out of the question - but IMHO I don't think that these "structures" should be inflated further.  There are already possibilities to arrange this elsewhere (ReflectionClass) if needed.

Maybe I lack creativity, I can think of a few cases why I need a different output format (connector-side!), with the objects you can do what you want in the end.

However, it makes sense for me to implement a logger in the connector.

**Pull request closed without merging**
